@echo off
:: =============================================================================
::  Zircon CLI Installer -- Windows
::  Installs the 'zircon' command so you can run it from any terminal.
::  Usage:  install_cli.bat   (run from the zirconAgent project folder)
:: =============================================================================

setlocal enabledelayedexpansion

title Zircon CLI Installer

cd /d "%~dp0"

echo.
echo  +----------------------------------------------------------+
echo  ^|                                                          ^|
echo  ^|   ZIRCON v1.0  --  CLI Installer for Windows            ^|
echo  ^|                                                          ^|
echo  +----------------------------------------------------------+
echo.

:: ── Check Python ────────────────────────────────────────────────────────────
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo   [ERROR] Python is not installed or not in PATH.
    echo   Install Python 3.10+ from https://www.python.org/downloads/
    pause
    exit /b 1
)

:: ── Resolve project root (this installer lives at project root) ──────────────
set "PROJ_ROOT=%~dp0"
:: %~dp0 always ends with \; strip it for clean path concatenation
if "%PROJ_ROOT:~-1%"=="\" set "PROJ_ROOT=%PROJ_ROOT:~0,-1%"

if not exist "%PROJ_ROOT%\cli\__init__.py" (
    echo   [ERROR] cli/ package not found in:
    echo           %PROJ_ROOT%
    echo   Run install_cli.bat from the zirconAgent project directory.
    pause
    exit /b 1
)

echo   Project root : %PROJ_ROOT%

:: ── Determine install directory ───────────────────────────────────────────────
set "INSTALL_DIR=%USERPROFILE%\.local\bin"
if not exist "%INSTALL_DIR%" (
    mkdir "%INSTALL_DIR%"
)

echo   Install dir  : %INSTALL_DIR%

:: ── Write zircon.cmd (project path is hardcoded at install time) ──────────────
::
::   Using %PROJ_ROOT% directly in the echo lines embeds the real path into
::   the generated file -- no runtime discovery needed or possible to get wrong.
::
set "LAUNCHER=%INSTALL_DIR%\zircon.cmd"

(
echo @echo off
echo :: =============================================================================
echo ::  zircon.cmd -- Zircon Agent CLI launcher ^(Windows^)
echo ::  Generated by install_cli.bat -- project root embedded at install time.
echo ::  Usage:  zircon [--low^|--quality^|--swarm] [workspace-path]
echo :: =============================================================================
echo.
echo :: Project root is hardcoded at install time. Re-run install_cli.bat if moved.
echo set "PROJECT_ROOT=%PROJ_ROOT%"
echo.
echo if not exist "%%PROJECT_ROOT%%\cli\__init__.py" ^(
echo     echo [ERROR] cli/ package not found. Re-run install_cli.bat to fix.
echo     echo         Expected: %%PROJECT_ROOT%%\cli\__init__.py
echo     pause
echo     exit /b 1
echo ^)
echo.
echo :: Route arguments:
echo ::   ^(no args^)       -- use CWD as workspace
echo ::   starts with --  -- flag^(s^) only, CWD is the workspace, args forwarded
echo ::   anything else   -- first arg is the workspace path, pass all through
echo set "FIRST=%%~1"
echo if "%%FIRST:~0,2%%"=="--" ^(
echo     python "%%PROJECT_ROOT%%\__main__.py" "%%CD%%" %%*
echo ^) else if "%%~1"=="" ^(
echo     python "%%PROJECT_ROOT%%\__main__.py" "%%CD%%"
echo ^) else ^(
echo     python "%%PROJECT_ROOT%%\__main__.py" %%*
echo ^)
echo.
echo if %%errorlevel%% neq 0 ^(
echo     echo.
echo     echo   [zircon] Process exited with error code %%errorlevel%%.
echo     pause
echo ^)
) > "%LAUNCHER%"

echo   Created: %LAUNCHER%

:: ── Ensure install dir is in user PATH ────────────────────────────────────────
echo.
echo   Checking PATH...

:: Read current user PATH from registry (may be absent on fresh accounts)
set "USER_PATH="
for /f "skip=2 tokens=2*" %%A in ('reg query HKCU\Environment /v PATH 2^>nul') do (
    set "USER_PATH=%%B"
    goto :path_got
)
:path_got

echo !USER_PATH! | find /i "%INSTALL_DIR%" >nul 2>&1
if %errorlevel% neq 0 (
    echo   Adding %INSTALL_DIR% to user PATH...
    if defined USER_PATH (
        setx PATH "%INSTALL_DIR%;!USER_PATH!" >nul
    ) else (
        setx PATH "%INSTALL_DIR%" >nul
    )
    if !errorlevel! equ 0 (
        echo   Done. Open a new terminal for the PATH change to take effect.
    ) else (
        echo.
        echo   [WARN] Could not update PATH automatically.
        echo   Add this directory to your user PATH manually:
        echo     %INSTALL_DIR%
    )
) else (
    echo   %INSTALL_DIR% is already in PATH.
)

echo.
echo  +----------------------------------------------------------+
echo  ^|   [OK] Zircon CLI installed successfully!               ^|
echo  +----------------------------------------------------------+
echo.
echo   Usage:
echo     zircon                       Open TUI in current directory
echo     zircon C:\path\to\project    Open TUI in a specific directory
echo     zircon --low                 Low tier mode
echo     zircon --quality             Quality tier with full planning
echo     zircon --swarm               Swarm mode
echo.
pause